#!/bin/bash

TMP="/tmp/socscan"

REPO="https://github.com/Greedtik/soc_scanner/archive/refs/heads/main.tar.gz"

echo "Downloading SOC Scanner..."

rm -rf $TMP
mkdir -p $TMP

curl -L $REPO | tar xz -C $TMP --strip-components=1

cd $TMP

chmod +x socscan.sh

sudo bash socscan.sh "$@"
